# Generated by Django 6.1.1 on 2026-09-27 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('masked_card_number', models.CharField(max_length=16)),
                ('card_fingerprint', models.CharField(max_length=64)),
                ('sheba', models.CharField(blank=True, max_length=36, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('external_http_status', models.IntegerField(blank=True, null=True)),
                ('external_reference_id', models.CharField(blank=True, max_length=64, null=True)),
                ('processing_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='inquiries_i_status_8fae14_idx'), models.Index(fields=['created_at'], name='inquiries_i_created_225eb3_idx'), models.Index(fields=['card_fingerprint'], name='inquiries_i_card_fi_c11ae6_idx')],
            },
        ),
    ]
